version: "3"

services:
  client:
    build: ./client
    env_file:
      - .env
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    volumes:
      - ./client:/data
    environment:
      - API_URL=${API_URL}

  server:
    build: ./server
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./server:/data
    depends_on:
      - server-database
    environment:
      - WAIT_HOSTS=${DB_URL}
      - DATABASE_URL=${DB_URL}

  server-database:
    image: mongo
    env_file:
      - .env
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./db:/data/db
