version: "3"

services:
  client:
    build: ./client
    env_file:
      - .env
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    volumes:
      - ./client:/data
    environment:
      - API_URL=${API_URL}

  server:
    build: ./server
    env_file:
      - .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./server:/data
    depends_on: 
      - server-database
    environment:
      - WAIT_HOSTS=server-database:27017
      - DATABASE_URL=server-database:27017
    
  server-database:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db

    