version: "3"

services:

  server-test:
    build:
      context: ./server
      dockerfile: Dockerfile.test
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./server:/data
    depends_on:
      - server-test-database
    environment:
      - WAIT_HOSTS=${TEST_DB_URL}
      - DATABASE_URL=${TEST_DB_URL}

  server-test-database:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/test_db
    #command: "mongod --smallfiles --logpath=${MONGO_LOG_FILE}"
