version: "3"

services:

  server-test:
    build:
      context: ./server
      dockerfile: Dockerfile.test
    ports:
      - 8081:8081
    volumes:
      - ./server:/data
    depends_on: 
      - server-test-database
    environment:
      - DATABASE_URL=server-database:27017
    
  server-test-database:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
    #command: "mongod --smallfiles --logpath=${MONGO_LOG_FILE}"