FROM task-manager_server

# Add WAIT
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait

RUN chmod +x /wait

ENV NODE_ENV test

# Copy or mount node app here
WORKDIR /data/

RUN npm install -g mocha

EXPOSE 8081

CMD /wait && npm run test
